version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khang2004
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./backup:/backup
    ports:
       - "5434:5432"
    networks:
       - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: khang2004
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
       - "5050:80"
    networks:
       - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: